-- MySQL Script generated by MySQL Workbench
-- 11/23/16 10:10:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `code postal` VARCHAR(5) NOT NULL,
  `tel` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agence` (
  `idagence` INT NOT NULL,
  `nom_de_l_agence` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `code postal` INT NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idagence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vehicule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vehicule` (
  `idvehicule` INT NOT NULL AUTO_INCREMENT,
  `nombredeporte` VARCHAR(45) NOT NULL,
  `nombredeplace` VARCHAR(45) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  `prixachat` VARCHAR(45) NOT NULL,
  `prixlocation` VARCHAR(45) NOT NULL,
  `transmission` VARCHAR(45) NOT NULL,
  `agence_idagence` INT NOT NULL,
  `climatisation` TINYINT(1) NOT NULL,
  `baggages` INT NOT NULL,
  `photo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idvehicule`),
  INDEX `fk_vehicule_agence_idx` (`agence_idagence` ASC),
  CONSTRAINT `fk_vehicule_agence`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `mydb`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrat_de_reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contrat_de_reservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contrat_de_reservation` (
  `idnumero_location` INT NOT NULL AUTO_INCREMENT,
  `date_resa` DATETIME NOT NULL,
  `date_debut_periode` DATETIME NOT NULL,
  `date_fin_periode` DATETIME NOT NULL,
  `client_idclient` INT NOT NULL,
  `vehicule_idvehicule` INT NOT NULL,
  `agence_idagencealler` INT NOT NULL,
  `agence_idagenceretour` INT NOT NULL,
  PRIMARY KEY (`idnumero_location`),
  INDEX `fk_contrat_de_reservation_client1_idx` (`client_idclient` ASC),
  INDEX `fk_contrat_de_reservation_vehicule1_idx` (`vehicule_idvehicule` ASC),
  INDEX `fk_contrat_de_reservation_agence1_idx` (`agence_idagencealler` ASC),
  INDEX `fk_contrat_de_reservation_agence2_idx` (`agence_idagenceretour` ASC),
  CONSTRAINT `fk_contrat_de_reservation_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrat_de_reservation_vehicule1`
    FOREIGN KEY (`vehicule_idvehicule`)
    REFERENCES `mydb`.`vehicule` (`idvehicule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrat_de_reservation_agence1`
    FOREIGN KEY (`agence_idagencealler`)
    REFERENCES `mydb`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrat_de_reservation_agence2`
    FOREIGN KEY (`agence_idagenceretour`)
    REFERENCES `mydb`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`concessionnaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`concessionnaire` ;

CREATE TABLE IF NOT EXISTS `mydb`.`concessionnaire` (
  `idconcessionnaire` INT NOT NULL AUTO_INCREMENT,
  `nom_concessionnaire` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `code_ postal` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idconcessionnaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`saison` ;

CREATE TABLE IF NOT EXISTS `mydb`.`saison` (
  `idSaison` INT NOT NULL AUTO_INCREMENT,
  `nomSaison` VARCHAR(10) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `debut` DATE NOT NULL,
  `fin` DATE NOT NULL,
  `pourcentage` FLOAT NOT NULL,
  PRIMARY KEY (`idSaison`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agence_has_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agence_has_client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agence_has_client` (
  `agence_idagence` INT NOT NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`client_idclient`),
  INDEX `fk_agence_has_client_client1_idx` (`client_idclient` ASC),
  INDEX `fk_agence_has_client_agence1_idx` (`agence_idagence` ASC),
  CONSTRAINT `fk_agence_has_client_agence1`
    FOREIGN KEY (`agence_idagence`)
    REFERENCES `mydb`.`agence` (`idagence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agence_has_client_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
